apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-service
  template:
    metadata:
      labels:
        app: payments-service
    spec:
      containers:
        - name: payments-service
          image: nginx:latest
          ports:
            - containerPort: 80
