apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/walabelhi/micro-app.git
    targetRevision: master
    path: k8s/tickets
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
